---
abstract: 'Parse USDA Food nutrition standard reference data files.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-USDASR
no_index:
  directory:
    - inc
    - t
requires:
  Rubyish: 0
version: 0.01
